### PR TITLE
Rework configuration to use LittleFS

### PR DESCRIPTION
**Pull request by TheDevMinerTV**
Recalibrate your IMUs! :D

### CODE REVIEW

**Comment by kitlith** [comment]
will this migrate existing on-flash configuration to littlefs on first run? (i.e. if flash is not already formatted as littlefs, check for existing configuration, then migrate?)

**Comment by TheDevMinerTV** [comment]
no, but this could be added in the future

**Comment by Eirenliel** [comment]
Don't see the reason, jsut re-calibrate :P

**Comment by TheDevMinerTV** [comment]
As I realized a couple hours ago: not even possible, LittleFS is in the exact same space as the EEPROM, so formatting the LittleFS basically wipes the existing configuration from existance.

**Comment by kitlith** [comment]
> As I realized a couple hours ago: not even possible, LittleFS is in the exact same space as the EEPROM, so formatting for LittleFS wipes the existing configuration from existance. 🤷‍♀️

That's whyvyou check for the pre-existing config *before* formatting.

that said, Eiren isn't concerned, so meh.

**Comment by TinyOra** [comment]
This really solved the problem of my 9250 : a certain probability that it will not work on startup( not sending data)
Thanks guys

**Pull request merged**
