### PR TITLE
feat: multiple wifi credentials

### PR DESCRIPTION
**Pull request by ZigTag**
I keep having to reset the credentials because I have multiple play spaces with two different login credentials, so I decided to make this to make my problem more bearable

### CODE REVIEW

**Comment by TheDevMinerTV** [comment]
I already have a better solution on hand, give me a few days to polish it up though :)

**Comment by ZigTag** [comment]
Would it be wise to reconsider this patch? Seems like #164 wasn't viable

**Comment by TheDevMinerTV** [comment]
Only if you're up to rewriting the WifiHandler into a class and refactoring some of the code in there (you can copy paste most stuff from my PR, probably).

**Comment by ZigTag** [comment]
Yeah I'd make it work on the newest versions, just asking if its worth the effort

**Comment by ZigTag** [comment]
Just to note, this patch is multiple HARDCODED wifi credentials, not multiple dynamic ones

**Pull request closed without merging**
