### PR TITLE
Set baudrate to 74880 for esp8266

### PR DESCRIPTION
**Pull request by deiteris**
This fixes garbage characters during boot at a cost of lower serial speed in general. Helps with debugging weird board issues by looking at the boot mode:
https://riktronics.wordpress.com/2017/10/02/esp8266-error-messages-and-exceptions-explained/
image

### CODE REVIEW

**Comment by deiteris** [comment]
This also requires a corresponding change to baud rate on the server side, otherwise it's all garbage in WiFi window :\

**Comment by Eirenliel** [comment]
I understand the idea, but this will make it incompatible with old firmware.. but probably now is the best time to do it.

**Comment by Eirenliel** [comment]
Ah, I see you set different baud rates for different controllers. This is bad, because server can't know which one is connected before it is, it's not user-friendly...

**Comment by deiteris** [comment]
Yeah, I realized this a bit later. Further idea was to detect baud rate based on the firmware and even gracefully handle compatibility with older firmware. Then I realized we don't report such data over serial...

The problem is that ESP32 uses 115200 baud for boot sequence, so if we keep 74800 baud for ESP8266, this will result in garbage boot log on ESP32. So we defo need a proper method to detect compatibility.

**Comment by Eirenliel** [comment]
I understand the problem, I don't like the solution though.

**Comment by Kamilake** [comment]
Is there any way to change its boot log to 115200?

**Comment by deiteris** [comment]
> Is there any way to change its boot log to 115200?

As far as I understand, no, this is controlled by bootloader that sets the baud rate depending on the crystal used.
https://stackoverflow.com/a/41011637

So this makes it a hardware issue that cannot be easily resolved by the software.

> I understand the problem, I don't like the solution though.

I mean, if someday we have some proper protocol over serial, this is the only user-friendly option because no manipulations would be required from the user. Otherwise, you could add baud rate selection for ESP8266 and ESP32 in the server, which is less convenient, but an option too.

I'll close this PR since this is not as easy problem as I was imagining it, but it is something to keep in mind since it would simplify troubleshooting.

**Comment by Kamilake** [comment]
> > Is there any way to change its boot log to 115200?
> 
> As far as I understand, no, this is controlled by bootloader that sets the baud rate depending on the crystal used. https://stackoverflow.com/a/41011637
> 
> So this makes it a hardware issue that cannot be easily resolved by the software.

Oh no... That was bad news. Why did Espressuf use unusual speeds? It never seems easy.

Thank you for the information.

**Pull request closed without merging**
