### PR TITLE
ESP-01 support + VCC Monitor

### PR DESCRIPTION
**Pull request by Levi--G**
ESP-01 support:
-Added defines
-Moved led operations to ledmgr
-Added option to disable LEDS
VCC monitor support:
-Added VCC monitor, not compatible with using internal ADC
-Every ESP has a slight offset to the actual voltage, but relative voltage is stable and usable
-Preliminary configuration will warn low battery at 3.2V and shut down at 3.1V

### CODE REVIEW

**Review by adigyran — APPROVED** [review]
Great work

**Comment by adigyran** [comment]
oh i have ESP-01 gonna see how it works

**Comment by Eirenliel** [comment]
why adding new led manager instead of expanding led status?

**Comment by Levi--G** [comment]
> why adding new led manager instead of expanding led status?

To be honest, i didn't quite get the purpose of the status class, it wasn't being used in the imu drivers or where the other leds were set in main etc and i don't know how i would add the calls to that class. The ledstatus also just handles the status led, while the other classes use the 2 other led numbers. But if you tell me how you want it added i can move it? :)

**Comment by Kamilake** [comment]
that seems to be very effective for diy users!

**Comment by Levi--G** [comment]
Just revised the battery system on my fork, moved the logic to a sepperate class and simplified code where available. Made slight adjustment to the defines to be a bit cleaner and added some explanation what does what. Also added compiler warnings for incompatible config.

**Comment by Eirenliel** [comment]
Pushed it in test branch, will do my own refactoring and some other changes before merging into main

**Pull request merged**
