### PR TITLE
Fix ENABLE_INSPECTION for BNO08x

### PR DESCRIPTION
**Pull request by deiteris**

### CODE REVIEW

**Review by Eirenliel — APPROVED** [review]

**Comment by TheDevMinerTV** [comment]
Must've bunged that up, sorry

**Comment by Eirenliel** [comment]
Fastest merge in this repo!

**Comment by deiteris** [comment]
my-job-here-is-done-bye

**Comment by Loler920a** [comment]
Hehehe testing noises testing noises

**Pull request merged**
