### PR TITLE
Add ClockStretchLimit/Timeout to ESP32 for BNO085

### PR DESCRIPTION
**Pull request by unlogisch04**
Need to be tested.

### CODE REVIEW

**Comment by Eirenliel** [comment]
Why are you adding this? Isn't 150ms the default anyway?

**Comment by unlogisch04** [comment]
Default is 50
grafik

**Comment by TheButlah** [comment]
is it 50 on the esp8266 or 150? what about by default on the esp32/c3?

**Comment by TheButlah** [comment]
I tested this code, it seems to fix timeouts in i2cscan. @unlogisch04 did you mean to mark this as a draft? Draft means the code is incomplete

**Comment by unlogisch04** [comment]
> @unlogisch04 did you mean to mark this as a draft? Draft usually means the code is incomplete
It was not tested if it rly helps. So I wanted to at least have some Feedback.

**Review by TheButlah — APPROVED** [review]

**Review by Eirenliel — APPROVED** [review]

**Comment by Eirenliel** [comment]
Build error was unrelated, merging.

**Pull request merged**
