### PR TITLE
Support dual MPU9250, change to dmp based fusion from mahony.

### PR DESCRIPTION
**Pull request by Boronare**
Calibration code from #32 : fixed memory leakage, etc...

Support multi MPUs.

Using dmp like MPU6050 with magnetic calibration based on direction cosine matrix.

Magnetic calibration can be tick-skipped, so it has close to 100 TPS.

Issue : Have to wait for reaching absolute rotation. Need initializing code to be added.
Issue2 : How to invoke calibration? I used "Turn on while flipped back, then flip again" to invoke calibration.

### CODE REVIEW

**Comment by deiteris** [comment]
Nice work! I tried to make a corrective quaternion to use with DMP fusion, but my results were not successful (I tried the code from here, but maybe that's not enough https://github.com/sslobodyan/MPU-9250DMP/blob/master/test.ino#L289). Is it actually better?

I'd also recommend to check my latest PR on MPU-9250 support. It uses continuous measurement mode that could help you to avoid skipping ticks for mag reading https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/53.

**Comment by Eirenliel** [comment]
Yeah if you can pull #53 here it would be nice, because i can't test #53 myself

**Comment by Boronare** [comment]
> Yeah if you can pull #53 here it would be nice, because i can't test #53 myself

Tested #53, not working... replied there.

**Comment by Eirenliel** [comment]
okay i'll leave it to you two @Boronare @deiteris for now, i don't have 9250 anyway and am busy with other PRs :D hmu when you think it's ready to merge. You don't *have to* merge #53... but that would mean i won't be able to merge one of these :D

**Comment by Boronare** [comment]
@Eirenliel I think it's ready to merge.

**Comment by Eirenliel** [comment]
Thanks! Will do when I deal with some stuff IRL

**Comment by LETS-BEE** [comment]
@Boronare I think magneto value is wrong in DMP packet.
File Here: ../lib/mpu9250/MPU9250MotionApps.cpp
`
// setup AK8963 (0x0C) as Slave 0 in read mode
DEBUG_PRINTLN(F("Setting up AK8963 read slave 0..."));
I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_ADDR, MPU9250_RA_MAG_ADDRESS|0x80);
I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_REG,  MPU9250_RA_MAG_XOUT_L);
I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_CTRL, 0xDA);
`
change here like this
`
// setup AK8963 (0x0C) as Slave 0 in read mode
DEBUG_PRINTLN(F("Setting up AK8963 read slave 0..."));
I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_ADDR, MPU9250_RA_MAG_ADDRESS|0x80);
I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_REG,  MPU9250_RA_MAG_WHOAMI);
I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_CTRL, 0xDA);
`
then we can read xyz value in DMP packet.

**Comment by LETS-BEE** [comment]
I don't know why but MPU9250_RA_MAG_WHOAMI is 0x01
INFO reg is right

And.. your right. magneto value do not use DMP. but passthrough in DMP packet. we can use acc, gyro with DMP and raw mag value. so i think if i use DMP acc, the calibrated gyro, and the mag calibrated using the raw mag of the DMP packet, I can get better quaternion value

oh, if i use MPU9250_RA_MAG_XOUT_L, I always have 0 value in z axis. but i use MPU9250_RA_MAG_WHOAMI (It's mean 0x01), I can read z value.

**Comment by deiteris** [comment]
I suspect that it is related to the `MPU9250_RA_I2C_SLV0_CTRL` setting. Could you try changing `I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_CTRL, 0xDA);` to `I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_CTRL, 0x97);`? It is supposed to read 7 bytes with grouping enabled and bit swap disabled.

**Comment by Boronare** [comment]
Oh,,, I may test it... but my project messed up to support ESP32-C3 RISC-V processor...
That code is from MPU9150s one so, It can be wrong for that. But as I remember, it worked.
Maybe MotionApps do something (byte-swap..) or this code is wrong...
I'll test and comment soon.

**Comment by LETS-BEE** [comment]
um...... my sensor's result is this
```
1. Axyz -2557   90      8382            Gxyz    1       -1      0               Mxyz    -16641  0       -2833
2. Axyz -4528   320     16112           Gxyz    20      7       -1              Mxyz    410     -67     3
1. Axyz -2557   94      8371            Gxyz    1       -1      0               Mxyz    -16641  0       -2833
2. Axyz -4564   292     16180           Gxyz    14      2       -3              Mxyz    410     -67     3
1. Axyz -2561   92      8382            Gxyz    1       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4552   392     16072           Gxyz    13      2       -3              Mxyz    410     -67     3
1. Axyz -2566   89      8385            Gxyz    0       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4524   288     16068           Gxyz    15      4       0               Mxyz    410     -67     3
1. Axyz -2564   91      8377            Gxyz    0       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4464   264     16056           Gxyz    22      6       0               Mxyz    410     -67     3
1. Axyz -2562   89      8376            Gxyz    0       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4424   304     15848           Gxyz    30      12      2               Mxyz    410     -67     3
1. Axyz -2550   84      8375            Gxyz    1       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4492   404     16080           Gxyz    30      14      1               Mxyz    410     -67     3
1. Axyz -2541   82      8349            Gxyz    1       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4508   372     16100           Gxyz    24      8       3               Mxyz    410     -67     3
1. Axyz -2537   91      8358            Gxyz    1       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4480   380     16004           Gxyz    15      1       2               Mxyz    410     -67     3
1. Axyz -2543   95      8367            Gxyz    1       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4496   340     16092           Gxyz    8       0       1               Mxyz    410     -66     1
1. Axyz -2538   97      8360            Gxyz    0       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4416   232     16072           Gxyz    2       1       0               Mxyz    410     -66     1
1. Axyz -2539   92      8354            Gxyz    0       -2      0               Mxyz    -16897  768     -3601
2. Axyz -4480   332     16076           Gxyz    5       5       -1              Mxyz    410     -66     1
1. Axyz -2534   81      8357            Gxyz    0       -1      0               Mxyz    -16897  768     -3601
2. Axyz -4432   180     15944           Gxyz    3       7       1               Mxyz    410     -66     1
1. Axyz -2529   76      8363            Gxyz    0       -1      0               Mxyz    -16641  256     -3089
2. Axyz -4540   232     16032           Gxyz    -1      21      1               Mxyz    410     -66     1
1. Axyz -2521   64      8347            Gxyz    0       -1      0               Mxyz    -16641  256     -3089
2. Axyz -4416   212     15880           Gxyz    4       31      1               Mxyz    410     -66     1
1. Axyz -2529   63      8342            Gxyz    0       -1      0               Mxyz    -16641  256     -3089
2. Axyz -4464   316     16096           Gxyz    22      45      4               Mxyz    410     -66     1
1. Axyz -2520   52      8328            Gxyz    0       0       0               Mxyz    -16641  256     -3089
2. Axyz -4624   228     16276           Gxyz    22      44      6               Mxyz    410     -66     1
1. Axyz -2521   55      8346            Gxyz    1       0       0               Mxyz    -16641  256     -3089
2. Axyz -4624   232     16188           Gxyz    18      31      1               Mxyz    410     -66     1
1. Axyz -2541   53      8372            Gxyz    1       0       0               Mxyz    -16641  256     -3089
2. Axyz -4564   260     16128           Gxyz    20      19      2               Mxyz    410     -66     1
1. Axyz -2555   47      8391            Gxyz    0       0       0               Mxyz    -16641  256     -3089
2. Axyz -4604   276     16088           Gxyz    12      13      1               Mxyz    410     -66     1
1. Axyz -2560   45      8393            Gxyz    1       -1      0               Mxyz    -16641  256     -3089
2. Axyz -4544   184     15848           Gxyz    8       12      -1              Mxyz    410     -66     1
1. Axyz -2567   49      8386            Gxyz    0       -1      0               Mxyz    -16641  256     -3089
2. Axyz -4568   292     16060           Gxyz    10      18      -4              Mxyz    410     -65     0
1. Axyz -2564   44      8356            Gxyz    0       -1      0               Mxyz    -16641  256     -3089
2. Axyz -4476   208     15956           Gxyz    11      21      -1              Mxyz    410     -65     0
1. Axyz -2560   51      8355            Gxyz    0       -1      0               Mxyz    -16641  256     -3089
2. Axyz -4628   228     16132           Gxyz    17      22      -1              Mxyz    410     -65     0
```
1. is the code of the DMP you suggested.
2. is getMostion9() function

when i use `I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_CTRL, 0xDA);` that result is same. but sometimes I have wrong value of getMotion9() fuction.

by the way, my sensor with DMP acc scale is 4G and gryo scale is 1000(not 2000). however when I  fix gyro scale to 875 that i have better quternion value.

**Comment by deiteris** [comment]
The values of `getMotion9()` seem to be fine if this 410 value is not static, and changes properly. This function was changed to work with raw values supplied by the SLV_0 sensor that's our magnetometer (https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/55/files#diff-a15dc9eeae3da47d5be8869ea5d8e22935fa90e13d73dce1ec93ff413264596dR1771).

> is the code of the DMP you suggested.

Okay, we probably have a small misunderstanding here. We do not read magnetometer data *from* DMP packet, since we don't know how to put magnetometer data *into* a DMP packet. What we do here, is just setting up a magnetometer as SLV_0 and then read the magnetometer data directly from the EXT_SENS_DATA registers in the `getMotion9()` function.

> when i use I2Cdev::writeByte(devAddr, MPU9250_RA_I2C_SLV0_CTRL, 0xDA); that result is same. but sometimes I have wrong value of getMotion9() fuction.

I think it's not just sometimes, since this result must be consistent.

> by the way, my sensor with DMP acc scale is 4G and gryo scale is 1000(not 2000). however when I fix gyro scale to 875 that i have better quternion value.

How or where exactly? 🤔 MPU doesn't have 875 gyro scale. If you say you have an improvement, you might need to recalibrate your sensor with the current initialization settings.

**Comment by Boronare** [comment]
@LETS-BEE How does it show if you rotate the sensor? Does it show same value?
Not like other sensors, magnetometer is not calibrated. It have to calculate bias then subtract from raw value.

**Comment by LETS-BEE** [comment]
@deiteris

> I think it's not just sometimes, since this result must be consistent.
it's right. but when I enabled DMP, I have wrong mag data.
so, I replug in mpu that I have correct data with disabled DMP.

@Boronare 

> How does it show if you rotate the sensor? Does it show same value?

yes. If i rotate the sensor, it show same value

And.... here is my test code using DMP packets.
```
mpu.dmpGetAccel(acc, fifoBuffer);
mpu.dmpGetGyro(gyro, fifoBuffer);
mpu.dmpGetMag(mag, fifoBuffer);

float Axyz[3];
Axyz[0] = (float)acc[0] * (4.f / 32768.f);
Axyz[1] = (float)acc[1] * (4.f / 32768.f);
Axyz[2] = (float)acc[2] * (4.f / 32768.f);

float Gxyz[3];
Gxyz[0] = (float)gyro[0] * (875.f / 32768.f);// * (PI / 180.0);
Gxyz[1] = (float)gyro[1] * (875.f / 32768.f);// * (PI / 180.0);
Gxyz[2] = (float)gyro[2] * (875.f / 32768.f);// * (PI / 180.0);
//Gxyz[0] = (float)gyro[0] * (1000.f / 32768.f);// * (PI / 180.0);
// Gxyz[1] = (float)gyro[1] * (1000.f / 32768.f);// * (PI / 180.0);
// Gxyz[2] = (float)gyro[2] * (1000.f / 32768.f);// * (PI / 180.0);

// (4912.f / 8190.f) 0.6 | (4912.f / 32760.f) 0.15
float Mxyz[3];
Mxyz[0] = (float)mag[0] * 0.15 * magadj[0];
Mxyz[1] = (float)mag[1] * 0.15 * magadj[1];
Mxyz[2] = (float)mag[2] * 0.15 * magadj[2];
```
I tested mahony filter without mag data. scale value 875 is my empirical value.
and i get same value that i test this another mpu9250 sensors with arduino uno.

**Comment by Eirenliel** [comment]
Please update it to the latest firmware changes

**Comment by Boronare** [comment]
Oh,,, there were lots of changes...
It may take a while.

I have to think about how to handle mag calibration data saved without isSecond param, or something else...

**Comment by Boronare** [comment]
By the way, I may touch server side to make 'invoke calibration' btn.
'Turn on while flipped back' is not intuitive.
Or... is it already there? Like... sending message to single tracker via utp.

**Comment by Eirenliel** [comment]
Yeah it's needed to be added

**Comment by Eirenliel** [comment]
If you're worried about saving, i am planning a per-sensor configuration storage in firmware, but i didn't get to it yet...

**Comment by Boronare** [comment]
@Eirenliel Done.

**Pull request merged**
