### PR TITLE
Replace the WiFiUDP library with the AsyncUDP library 

### PR DESCRIPTION
**Pull request by Sark1tama**
Tested available at ESP32, Ping min 1-3ms, average less than 10ms, and stable. When using SEND_UPDATES_UNCONNECTED may cause packet reception failure before handshake is completed.

### CODE REVIEW

**Comment by Eirenliel** [comment]
Is there any reason why this is better than what was before?

**Comment by Sark1tama** [comment]
> Is there any reason why this is better than what was before?

The AsyncUDP library uses FreeRTOS to make UDP sending and receiving asynchronous

**Comment by Eirenliel** [comment]
> > Is there any reason why this is better than what was before?
> 
> The AsyncUDP library uses FreeRTOS to make UDP sending and receiving asynchronous

Ah, it's for ESP32, and for ESP8266 it uses ESPAsyncUDP to have the same interface. This would require a lot of testing for ESP8266 before it can be merged, because ESP8266 is the main target platform.

**Comment by Eirenliel** [comment]
Can you replace the library with https://github.com/OttoWinter/ESPAsyncTCP ? It's the fork used in Esphome, i trust it to work more as it looks maintainted better.

**Comment by Eirenliel** [comment]
Forget the comment I just posted and removed :P bad reading comprehension, sorry!

**Pull request closed without merging**
