### PR TITLE
Replace madgwick and mahony with fusion library

### PR DESCRIPTION
**Pull request by sctanf**
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/issues/216

not tested - ci fail since it tries to compile everything in the submodule..

### CODE REVIEW

**Comment by nekomona** [comment]
Found a PlatformIO wrapper for the library [here](https://registry.platformio.org/libraries/nut-code-monkey/Fusion%20AHRS)

Should help the dependency solving process for PIO if use it and commit all the files to the lib dir.

**Comment by sctanf** [comment]
> Found a PlatformIO wrapper for the library [here](https://registry.platformio.org/libraries/nut-code-monkey/Fusion%20AHRS)
> 
> Should help the dependency solving process for PIO if use it and commit all the files to the lib dir.

thanks! but seems outdated, I copied the files in the meantime

**Comment by unlogisch04** [comment]
is this pr still valid? As there where a lot of changes with separation?

**Comment by sctanf** [comment]
maybe superseded now that vqf can be used on everything, no reason to work on this

**Comment by unlogisch04** [comment]
Hm as in https://github.com/SlimeVR/SlimeVR-Tracker-ESP/issues/216 the main thing was because of some unclear stuff in license . 
But i think it has do adopted to work with the new code basis.

**Comment by l0ud** [comment]
VQF is MIT, I have a long term plan to remove both madgwick and mahony.

**Comment by unlogisch04** [comment]
https://github.com/xioTechnologies/Fusion is also MIT so i don't see a problem.

**Pull request closed without merging**
